package main

import (
	"log"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"github.com/mixdive/feedback-platform/api"
	"github.com/mixdive/feedback-platform/api/console"
	"github.com/mixdive/feedback-platform/api/middlewares"
	"github.com/mixdive/feedback-platform/api/portal"
	"github.com/mixdive/feedback-platform/dataoperations"
	"github.com/mixdive/feedback-platform/pkg/aianalyzer"
	"github.com/mixdive/feedback-platform/pkg/storage"
	"github.com/mixdive/feedback-platform/web"

	// Generated by `swag init`. The blank import wires the OpenAPI doc into
	// `swag.Register(...)` so gin-swagger can serve it.
	_ "github.com/mixdive/feedback-platform/docs/api"
)

// newRouter wires every HTTP route and middleware. The Console is gated by
// AttachUser + RequireConsoleAccess; the Portal always requires an
// authenticated user (no anonymous-read path).
//
// worker is the AI analyzer poller. It runs independently in the
// background; it is threaded through here only so the upcoming AI
// settings + queue stats handlers (chunk 4) can refresh its snapshot
// and read its Stats. Entry-create/edit handlers do NOT touch it —
// the worker discovers new and edited entries by polling Mongo.
func newRouter(do *dataoperations.DataOperations, store *storage.Holder, worker *aianalyzer.Worker) *gin.Engine {
	r := gin.Default()

	// System.
	r.GET("/health", api.HealthHandler(do))
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Files. The serve endpoint is intentionally public — UUID is the only
	// access token, mirroring how Slack/Notion/GitHub serve attachments.
	// Upload endpoints sit under each surface so they share that surface's
	// middleware stack (write-access gate on Portal, console-access gate on
	// Console). Both surfaces hand off to the same shared handler.
	r.GET("/api/files/:id", api.GetFileHandler(do, store))

	// Setup (first-run wizard). Public; POST refuses once setup is done.
	r.GET("/api/setup/status", api.SetupStatusHandler(do))
	r.POST("/api/setup", api.SetupHandler(do))

	// Auth. Login is public; /me + /logout need the cookie attached so they
	// can resolve the current session.
	attachUser := middlewares.AttachUserMiddleware(do)
	r.POST("/api/login", api.LoginHandler(do))
	r.POST("/api/logout", attachUser, api.LogoutHandler(do))
	r.GET("/api/me", attachUser, api.MeHandler(do))

	// Portal. RequireSetupCompleted runs first. /config is always reachable
	// once setup is complete — the visitor needs it to discover whether
	// custom auth is on and which URL to redirect to. The read group adds
	// AttachUser plus the require-auth gate.
	pgConfig := r.Group("/api/portal",
		middlewares.RequireSetupCompletedMiddleware(do),
	)
	{
		pgConfig.GET("/config", portal.GetConfigHandler(do))
	}
	pgPublic := r.Group("/api/portal",
		middlewares.RequireSetupCompletedMiddleware(do),
	)
	{
		pgPublic.POST("/auth/custom", portal.LoginCustomHandler(do))
		pgPublic.POST("/auth/google", portal.LoginGoogleHandler(do))
		// Changelog is intentionally public so the marketing/landing flow
		// can link to /changelog without requiring a sign-in. Only
		// completed releases surface here.
		pgPublic.GET("/changelog", portal.ListChangelogHandler(do))
		// Detail endpoint backs the per-release shareable URLs the
		// Portal links to from /changelog. Slug accepts version name
		// or ID; both planned and completed releases resolve.
		pgPublic.GET("/changelog/:slug", portal.GetChangelogReleaseHandler(do))
	}
	pgRead := r.Group("/api/portal",
		middlewares.RequireSetupCompletedMiddleware(do),
		attachUser,
		middlewares.RequirePortalReadAccessMiddleware(do),
	)
	{
		pgRead.GET("/entry", portal.ListEntriesHandler(do))
		pgRead.GET("/entry/:id", portal.GetEntryHandler(do))
		pgRead.GET("/entry/:id/comment", portal.ListCommentsHandler(do))
	}
	pgWrite := r.Group("/api/portal",
		middlewares.RequireSetupCompletedMiddleware(do),
		attachUser,
		middlewares.RequirePortalWriteAccessMiddleware(do),
	)
	{
		pgWrite.POST("/entry", portal.SubmitEntryHandler(do))
		// Synchronous AI similarity search for the create-entry flow.
		// Reads worker.Snapshot for the live AI config without restart.
		pgWrite.POST("/entry/find-similar", portal.FindSimilarHandler(do, worker))
		// Voting needs identity for the one-vote-per-user rule, even when
		// portal writes are otherwise anonymous. RequireUser is applied at
		// the route level so SubmitEntryHandler keeps its existing
		// anonymous-allowed behavior. Commenting is similarly auth-only —
		// every comment carries the author's user ID.
		pgWrite.POST("/entry/:id/vote",
			middlewares.RequireUserMiddleware(),
			portal.AddVoteHandler(do),
		)
		pgWrite.POST("/entry/:id/comment",
			middlewares.RequireUserMiddleware(),
			portal.CreateCommentHandler(do),
		)
		pgWrite.POST("/files",
			middlewares.RequireUploadsEnabledMiddleware(do),
			api.UploadFileHandler(do, store),
		)
	}

	// Console. Setup must be complete and the request must carry a valid
	// session cookie. The bulk of the Console (settings + entries) is open
	// to admins and editors via RequireConsoleAccess; mutating settings
	// (PATCH /settings) is admin-only — editors can view but not change
	// project/entry/portal/team configuration.
	cg := r.Group("/api/console",
		middlewares.RequireSetupCompletedMiddleware(do),
		attachUser,
		middlewares.RequireConsoleAccessMiddleware(),
	)
	{
		cg.GET("/dashboard", console.GetDashboardHandler(do))
		cg.GET("/me", console.GetMyProfileHandler(do))
		cg.PATCH("/me", console.UpdateMyProfileHandler(do))
		cg.POST("/me/password", console.UpdateMyPasswordHandler(do))

		cg.GET("/settings", console.GetSettingsHandler(do, store))
		cg.PATCH("/settings",
			middlewares.RequireAdminMiddleware(),
			console.UpdateSettingsHandler(do, store),
		)
		cg.PATCH("/settings/ai",
			middlewares.RequireAdminMiddleware(),
			console.UpdateAISettingsHandler(do, worker, store),
		)
		// Integrations live under their own endpoint family rather than
		// nested under /settings — separate page in the Console nav,
		// separate lifecycle (Connect verifies against GitHub before
		// persisting; Disconnect zeroes credentials atomically).
		cg.GET("/integrations", console.GetIntegrationsHandler(do))
		cg.PUT("/integrations/github",
			middlewares.RequireAdminMiddleware(),
			console.UpdateGitHubIntegrationHandler(do),
		)
		cg.DELETE("/integrations/github",
			middlewares.RequireAdminMiddleware(),
			console.DeleteGitHubIntegrationHandler(do),
		)
		cg.GET("/ai/queue",
			middlewares.RequireAdminMiddleware(),
			console.GetAIQueueHandler(worker),
		)

		cg.GET("/entry", console.ListEntriesHandler(do))
		cg.GET("/entry-author", console.ListEntryAuthorsHandler(do))
		// Topics: list is admin+editor (editors apply topics to
		// entries from the entry edit form); the topic set itself
		// is admin-managed.
		cg.GET("/entry-topic", console.ListEntryTopicsHandler(do))
		cg.POST("/entry-topic",
			middlewares.RequireAdminMiddleware(),
			console.CreateEntryTopicHandler(do),
		)
		cg.PATCH("/entry-topic/:id",
			middlewares.RequireAdminMiddleware(),
			console.UpdateEntryTopicHandler(do),
		)
		cg.DELETE("/entry-topic/:id",
			middlewares.RequireAdminMiddleware(),
			console.DeleteEntryTopicHandler(do),
		)
		// Releases: list/get is admin+editor (editors assign entries to
		// releases from the entry edit form); the release set itself is
		// admin-managed.
		cg.GET("/release", console.ListReleasesHandler(do))
		cg.GET("/release/:id", console.GetReleaseHandler(do))
		cg.POST("/release",
			middlewares.RequireAdminMiddleware(),
			console.CreateReleaseHandler(do),
		)
		cg.PATCH("/release/:id",
			middlewares.RequireAdminMiddleware(),
			console.UpdateReleaseHandler(do),
		)
		cg.DELETE("/release/:id",
			middlewares.RequireAdminMiddleware(),
			console.DeleteReleaseHandler(do),
		)
		cg.GET("/entry/:id", console.GetEntryHandler(do))
		cg.PATCH("/entry/:id", console.UpdateEntryHandler(do))
		cg.POST("/entry/:id/vote", console.AddVoteHandler(do))
		cg.GET("/entry/:id/comment", console.ListCommentsHandler(do))
		cg.GET("/entry/:id/activity", console.ListActivitiesHandler(do))
		cg.PATCH("/entry/:id/comment/:commentId", console.UpdateCommentHandler(do))
		// Relations are Console-only — admins/editors link entries to
		// each other (e.g. duplicate, related). Symmetric: each
		// mutation touches both entries.
		cg.POST("/entry/:id/relation", console.AddEntryRelationHandler(do))
		cg.DELETE("/entry/:id/relation/:peerEntryId", console.DeleteEntryRelationHandler(do))
		// Merge folds a source entry into a target: links them as
		// duplicates, transfers unique votes, cancels the source, and
		// appends a system comment. Console-only (admin/editor).
		cg.POST("/entry/:id/merge", console.MergeEntryHandler(do))
		// Publish a feature-request or bug as a GitHub issue under the
		// repo wired in Settings → Integrations. AI summarises the
		// entry; the handler appends a Mixdive back-link. Admin+editor
		// (mirrors the rest of per-entry mutations).
		cg.POST("/entry/:id/github-issue", console.CreateGitHubIssueHandler(do))

		cg.POST("/files",
			middlewares.RequireUploadsEnabledMiddleware(do),
			api.UploadFileHandler(do, store),
		)

		// Listing the administrator + user roster is read-only; editors see
		// it too. Mutations to roles or block status are admin-only — only
		// admins can change who else can log in to the Console.
		cg.GET("/administrator", console.ListAdministratorsHandler(do))
		cg.GET("/user", console.ListUsersHandler(do))
		cg.PATCH("/user/:id/roles",
			middlewares.RequireAdminMiddleware(),
			console.UpdateUserRolesHandler(do),
		)
		cg.PATCH("/user/:id/block",
			middlewares.RequireAdminMiddleware(),
			console.UpdateUserBlockHandler(do),
		)
	}

	if err := web.Mount(r, do); err != nil {
		log.Printf("mixdive: spa mount: %v", err)
	}

	return r
}
